const $=id=>document.getElementById(id);
const levels=[{n:2,name:'왕초급',icon:'🌱',desc:'첫 숫자 친구',tint:'#ecf1df',border:'#dce5cc'},{n:3,name:'초급',icon:'🌼',desc:'조금씩 피어나는 자신감',tint:'#fbf1d7',border:'#eee1bc'},{n:4,name:'중급',icon:'🌳',desc:'생각이 자라는 시간',tint:'#e5eee5',border:'#d2e1d4'},{n:5,name:'고급',icon:'🦊',desc:'반짝이는 추리력',tint:'#f8e8dc',border:'#ecd6c6'},{n:6,name:'왕고급',icon:'🦉',desc:'숫자 숲의 달인',tint:'#eae7f2',border:'#dcd6e9'}];
let n=2,stage=1,game=null,selected=-1,paused=false,finished=false,elapsed=0,started=0,hints=0,history=[],screen='home',records=[];
try{records=JSON.parse(localStorage.getItem('number-forest-records')||'[]');if(!Array.isArray(records))records=[];records=records.filter(r=>r&&typeof r.name==='string'&&Number.isFinite(r.ms)&&r.ms>=0&&r.n>=2&&r.n<=6&&r.stage>=1&&r.stage<=10);$('player').value=localStorage.getItem('number-forest-player')||'';}catch{records=[];}
const name=()=>$('player').value.trim().slice(0,16)||'숲속 탐험가';
function save(){try{localStorage.setItem('number-forest-records',JSON.stringify(records));localStorage.setItem('number-forest-player',name());return true;}catch{return false;}}
function format(ms){const d=Math.floor(ms/100),s=Math.floor(d/10);return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')+'.'+d%10;}
function time(){return elapsed+(!paused&&!finished&&screen==='play'?performance.now()-started:0);}
function show(id){screen=id;for(const v of ['home','stages','play'])$(v).hidden=v!==id;window.scrollTo({top:0,behavior:'instant'});}
function filtered(size,board,mode='race'){return records.filter(r=>r.n===size&&r.stage===board&&(mode==='race'?r.hints===0:r.hints>0)).sort((a,b)=>a.ms-b.ms);}
function stages(){show('stages');const l=levels[n-2];$('stage-title').textContent=l.icon+' '+l.name+' · '+n+'×'+n;$('stage-grid').replaceChildren();for(let k=1;k<=10;k++){const b=document.createElement('button'),best=filtered(n,k)[0];b.className='stage'+(best?' completed':'');b.innerHTML='<strong>'+String(k).padStart(2,'0')+' <small>'+(best?'✓':'')+'</small></strong><span>'+(best?'최고 '+format(best.ms):'새로운 도전 →')+'</span>';b.onclick=()=>start(k);$('stage-grid').append(b);}}
levels.forEach(l=>{const b=document.createElement('button');b.className='level';b.style.setProperty('--tint',l.tint);b.style.setProperty('--border',l.border);b.innerHTML='<span class="emoji">'+l.icon+'</span><h3>'+l.name+'</h3><p>'+l.desc+'</p><span class="size">'+l.n+' × '+l.n+'</span><span class="arrow">↗</span>';b.onclick=()=>{n=l.n;save();stages();};$('levels').append(b);const o=document.createElement('option');o.value=l.n;o.textContent=l.name;$('record-level').append(o);});
for(let i=1;i<=10;i++){const o=document.createElement('option');o.value=i;o.textContent=i+'번 판';$('record-stage').append(o);}
function start(k){stage=k;const seed=crypto.getRandomValues(new Uint32Array(1))[0];game=Sudoku.puzzle(n,stage,seed);game.values=game.puzzle.slice();history=[];hints=0;paused=false;finished=false;elapsed=0;selected=game.puzzle.findIndex(v=>!v);show('play');started=performance.now();$('pause-cover').hidden=true;$('board').style.visibility='visible';$('player-label').textContent='🌿 '+name();$('game-level').textContent=levels[n-2].name+' · '+n+'×'+n;$('game-title').textContent=stage+'번 숲 탐험';$('rules').textContent='1부터 '+n+'까지 숫자가 가로줄과 세로줄에 한 번씩만 들어가게 채워요.'+([4,6].includes(n)?' 굵은 선으로 나눈 2×'+n/2+' 구역 안에서도 숫자가 겹치면 안 돼요.':' 이 크기의 판은 작은 구역 규칙 없이 가로·세로로만 풀어요.');const best=filtered(n,stage)[0];$('best-time').textContent=best?format(best.ms):'첫 기록에 도전!';$('best-player').textContent=best?best.name:'';$('keypad').replaceChildren();for(let v=1;v<=n;v++){const b=document.createElement('button');b.textContent=v;b.setAttribute('aria-label',v+' 입력');b.onclick=()=>enter(v);$('keypad').append(b);}$('feedback').textContent='빈칸을 누른 다음 숫자를 골라 주세요.';render();}
function render(){const board=$('board');board.style.setProperty('--n',n);board.replaceChildren();let filled=0,total=0;game.values.forEach((v,i)=>{const b=document.createElement('button'),r=Math.floor(i/n),c=i%n,given=!!game.puzzle[i],conflict=v&&game.values.some((w,j)=>i!==j&&w===v&&Sudoku.peers(i,j,n));b.className='cell'+(given?' given':'')+(selected>=0&&Sudoku.peers(i,selected,n)?' peer':'')+(v&&v===game.values[selected]?' same':'')+(i===selected?' selected':'')+(conflict?' wrong':'')+([4,6].includes(n)&&c<n-1&&(c+1)%(n/2)===0?' box-right':'')+([4,6].includes(n)&&r<n-1&&(r+1)%2===0?' box-bottom':'');b.textContent=v||'';b.dataset.index=i;b.setAttribute('aria-label',(r+1)+'행 '+(c+1)+'열 '+(v||'빈칸')+(given?' 주어진 숫자':''));b.setAttribute('aria-pressed',String(i===selected));b.onclick=()=>{if(paused||finished)return;selected=i;render();};board.append(b);if(!given){total++;if(v)filled++;}});$('progress-text').textContent=filled+' / '+total+'칸 채웠어요';$('progress').value=filled/total;$('hint-count').textContent=hints?'💡 힌트 '+hints+'번 · 연습 모드':'✦ 실력 모드';$('undo').disabled=!history.length||paused||finished;for(const id of ['erase','hint','pause'])$(id).disabled=paused||finished;for(const b of $('keypad').children)b.disabled=paused||finished;}
function enter(v){if(paused||finished||screen!=='play')return;if(selected<0||game.puzzle[selected]){$('feedback').textContent='주어진 숫자는 바꿀 수 없어요. 빈칸을 골라 주세요.';return;}if(game.values[selected]===v)return;history.push({i:selected,v:game.values[selected]});game.values[selected]=v;const conflict=v&&game.values.some((w,j)=>j!==selected&&w===v&&Sudoku.peers(j,selected,n));$('feedback').textContent=conflict?'같은 숫자가 겹쳤어요. 빨간 칸을 다시 살펴봐요.':'좋아요! 한 칸씩 생각해 봐요.';render();if(Sudoku.valid(game.values,n))complete();else if(game.values.every(Boolean))$('feedback').textContent='모두 채웠어요! 숫자가 겹친 곳을 다시 살펴보세요.';}
function complete(){elapsed=time();finished=true;const record={name:name(),n,stage,ms:Math.round(elapsed),hints,date:new Date().toISOString()};records.push(record);const saved=save();$('result-name').textContent=name()+', 끝까지 해냈어요!';$('result-time').textContent=format(elapsed);const place=filtered(n,stage,hints?'practice':'race').indexOf(record)+1;$('result-detail').textContent=(hints?'힌트 '+hints+'번 · 연습 기록':'이 판의 실력 기록 '+place+'위!')+(saved?' 저장했어요.':' — 저장 공간을 사용할 수 없어 이번 기록은 화면을 닫으면 사라져요.');render();$('result').showModal();}
function pause(){if(screen!=='play'||finished||paused)return;elapsed=time();paused=true;$('pause-cover').hidden=false;$('board').style.visibility='hidden';render();}
function resume(){if(!paused)return;paused=false;started=performance.now();$('pause-cover').hidden=true;$('board').style.visibility='visible';render();}
$('erase').onclick=()=>enter(0);$('undo').onclick=()=>{if(paused||finished||!history.length)return;const last=history.pop();game.values[last.i]=last.v;selected=last.i;render();$('feedback').textContent='한 칸 되돌렸어요.';};$('hint').onclick=()=>{if(paused||finished)return;let i=selected;if(i<0||game.puzzle[i]||game.values[i]===game.solution[i])i=game.values.findIndex((v,j)=>!game.puzzle[j]&&v!==game.solution[j]);if(i<0)return;selected=i;hints++;enter(game.solution[i]);$('feedback').textContent='힌트로 한 칸을 채웠어요. 이번 판은 연습 기록으로 남아요.';};$('pause').onclick=pause;$('resume').onclick=resume;
$('leave').onclick=()=>{if(finished){stages();return;}pause();$('exit-dialog').showModal();};$('keep-playing').onclick=()=>{$('exit-dialog').close();resume();};$('confirm-leave').onclick=()=>{$('exit-dialog').close();stages();};$('exit-dialog').addEventListener('cancel',()=>resume());
$('stages-back').onclick=()=>show('home');document.querySelector('.brand').onclick=e=>{e.preventDefault();if(screen==='play'&&!finished){$('leave').click();return;}show('home');};$('random').onclick=()=>start(1+Math.floor(Math.random()*10));$('next').onclick=()=>{$('result').close();start(stage%10+1);};$('result-close').onclick=()=>{$('result').close();stages();};$('result').addEventListener('cancel',()=>stages());
function recordList(){const list=filtered(Number($('record-level').value),Number($('record-stage').value),$('record-mode').value);$('record-list').replaceChildren();if(!list.length){const p=document.createElement('p');p.className='muted';p.textContent='아직 기록이 없어요. 첫 번째 주인공이 되어 보세요!';$('record-list').append(p);}list.slice(0,30).forEach((r,i)=>{const row=document.createElement('div');row.className='record-row';const rank=document.createElement('b');rank.textContent=i+1;const who=document.createElement('span');who.textContent=r.name;const date=document.createElement('small');date.textContent=new Date(r.date).toLocaleDateString('ko-KR');who.append(date);const t=document.createElement('strong');t.textContent=format(r.ms);row.append(rank,who,t);$('record-list').append(row);});}
$('records-open').onclick=()=>{pause();$('record-level').value=n;$('record-stage').value=stage;recordList();$('records').showModal();};$('records-close').onclick=()=>$('records').close();for(const id of ['record-level','record-stage','record-mode'])$(id).onchange=recordList;
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});document.addEventListener('keydown',e=>{if(screen!=='play'||paused||finished||document.querySelector('dialog[open]'))return;if(/^[1-6]$/.test(e.key)&&Number(e.key)<=n){e.preventDefault();enter(Number(e.key));}else if(['Backspace','Delete','0'].includes(e.key)){e.preventDefault();enter(0);}else{const shift={ArrowLeft:-1,ArrowRight:1,ArrowUp:-n,ArrowDown:n}[e.key];if(shift){e.preventDefault();selected=Math.max(0,Math.min(n*n-1,selected+shift));render();$('board').children[selected].focus();}}});
setInterval(()=>{if(screen==='play')$('time').textContent=format(time());},80);
