(function(root){
function rng(seed){return ()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return ((t^t>>>14)>>>0)/4294967296;};}
function shuffle(a,random){a=a.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function boxSize(n){return Math.round(Math.sqrt(n));}
function peers(a,b,n){const k=boxSize(n),ar=Math.floor(a/n),br=Math.floor(b/n),ac=a%n,bc=b%n;return ar===br||ac===bc||(Math.floor(ar/k)===Math.floor(br/k)&&Math.floor(ac/k)===Math.floor(bc/k));}
function solve(board,n,limit=2){let count=0,answer;const grid=board.slice();function visit(){let best=-1,choices=[];for(let i=0;i<grid.length;i++){if(grid[i])continue;const possible=Array.from({length:n},(_,k)=>k+1).filter(v=>!grid.some((x,j)=>x===v&&peers(i,j,n)));if(!possible.length)return;if(best<0||possible.length<choices.length){best=i;choices=possible;if(choices.length===1)break;}}if(best<0){count++;answer=grid.slice();return;}for(const v of choices){grid[best]=v;visit();grid[best]=0;if(count>=limit)return;}}visit();return {count,answer};}
function valid(board,n){return board.length===n*n&&board.every((v,i)=>Number.isInteger(v)&&v>=1&&v<=n&&!board.some((w,j)=>j!==i&&v===w&&peers(i,j,n)));}
function bank(n){const k=boxSize(n),random=rng(n*98471),out=[];for(let stage=0;stage<10;stage++){const symbols=shuffle(Array.from({length:n},(_,i)=>i+1),random);const solution=Array.from({length:n*n},(_,i)=>{const r=Math.floor(i/n),c=i%n;return symbols[((r*k)+Math.floor(r/k)+c)%n];});const puzzle=solution.slice();const holes=Math.floor(n*n*(n>=25?.72:n>=16?.62:n===9?.58:.5));for(const i of shuffle(Array.from({length:n*n},(_,i)=>i),random).slice(0,holes))puzzle[i]=0;if(n<=9){for(const i of shuffle(Array.from({length:n*n},(_,i)=>i),random)){if(puzzle.filter(x=>!x).length<=Math.floor(n*n*.42))break;const old=puzzle[i];puzzle[i]=0;if(solve(puzzle,n).count!==1)puzzle[i]=old;}}out.push({puzzle,solution});}return out;}
const banks={};
function puzzle(n,stage,seed){if(!banks[n])banks[n]=bank(n);const base=banks[n][stage-1],random=rng(seed),symbols=shuffle(Array.from({length:n},(_,i)=>i+1),random),flipX=random()<.5,flipY=random()<.5;const transform=a=>Array.from({length:n*n},(_,i)=>{const r=Math.floor(i/n),c=i%n,v=a[(flipY?n-1-r:r)*n+(flipX?n-1-c:c)];return v?symbols[v-1]:0;});return {puzzle:transform(base.puzzle),solution:transform(base.solution)};}
root.Sudoku={rng,peers,solve,valid,bank,puzzle,boxSize};
})(globalThis);
